version: '3.7'

services:
    mysql_server:
        image: mysql
        container_name: mysql_server
        volumes:
            - ./database:/var/lib/mysql
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: miniproj4_db
            MYSQL_USER: miniproj4_root
            MYSQL_PASSWORD: r1234
        ports:
        - '3306:3306'
